# Generated by Django 4.0.2 on 2022-02-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wearable',
            fields=[
                ('user_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('timeStamp', models.CharField(max_length=500)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch.sensor')),
                ('wearable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch.wearable')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='wearable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch.wearable'),
        ),
    ]
