# Generated by Django 4.0.2 on 2022-03-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HRFrequency', models.CharField(max_length=500)),
                ('TemperatureFrequency', models.CharField(max_length=500)),
                ('HRVFrequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch.sensor')),
                ('numberOfWearables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch.wearable')),
            ],
        ),
    ]
