# Generated by Django 4.0.2 on 2022-03-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0002_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='HRFrequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='HRVFrequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='TemperatureFrequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='numberOfWearables',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
