# Generated by Django 4.0.2 on 2022-03-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0003_alter_configuration_hrfrequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='BatchFrequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
